### ISSUE TITLE
full screen vertical video

### ISSUE THREAD

**Issue by tomcounsell** [yudame/bemmerse-ios#7]
When playing any video, it should go full-screen.
Only need to test using vertical videos. We will not be showing any horizontal videos in Bemmerse app v1

**Comment by Brbb** [comment]
@tomcounsell how do we manage cropped videos? they will show upper/lower black bands.

**Comment by tomcounsell** [comment]
all videos in the API will be 9:16 ratio
we are pre-processing all to 9:16 so if there are black bars, it's because we added them instead of cropping
